docs(publish): document publishing and deploying via CLI
enarx/website pull request #41
Opened 2022-07-06 16:26 UTC by bstrie

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-07-06 16:37 UTC, platten requested changes
Please move `docs/Running/Publish.md` to `override/Running/Publish.md` and create a PR to add `Running/Publish.md` under the `docs` directory in the `enarx` repository.

2022-07-06 16:37 UTC, platten commented on docs/Running/Publish.md
> +# Publishing and deploying applications via Enarx
This documentation should be versioned. As we are post-release, we will need to use an override until the next upcoming release. To do this, create a directory called "override" in the root and put the documents there (as well as please commit this to the enarx repository under docs for the upcoming release).

2022-07-07 15:13 UTC, nickvidal approved these changes
Looks good, but I wasn't able to test it, as I got this error message while trying to register myself: 

```
Error: Failed to save user credentials
Caused by:
    0: Platform secure storage failure: zbus error: D-Bus handshake failed: Unexpected server AUTH reply
    1: zbus error: D-Bus handshake failed: Unexpected server AUTH reply
    2: D-Bus handshake failed: Unexpected server AUTH reply
```

2022-07-07 18:03 UTC, bstrie commented
@nickvidal What platform are you on?

2022-07-07 20:15 UTC, nickvidal commented
> @nickvidal What platform are you on?

Ubuntu 22.04

2022-07-08 14:55 UTC, platten commented
Closing in favor of #42 which includes fixes

2022-07-08 14:55 UTC, closed without merging